/**
 * Blog locales — top 10 markets for the MagicFeed Pro SaaS audience.
 * Ranked by combined criteria: e-commerce GMV, Google Shopping
 * footprint, language reach, and B2B SaaS conversion potential for a
 * product targeted at Google Shopping advertisers.
 *
 * Order matters: en is the default (publishes first), the others are
 * generated by the AI editor with translations seeded from EN.
 *
 *  en  — English (US/UK/AU)            — primary
 *  es  — Spanish (Spain + LATAM)
 *  fr  — French (FR/BE/CH/CA)
 *  de  — German (DE/AT/CH — largest EU e-commerce market)
 *  it  — Italian
 *  pt  — Portuguese (Brazil + PT)
 *  nl  — Dutch (NL/BE — highest per-capita e-commerce in EU)
 *  pl  — Polish (fastest-growing e-commerce in EU)
 *  sv  — Swedish (Nordics gateway)
 *  ja  — Japanese (3rd-largest e-commerce market globally)
 */
export const locales = [
  'en',
  'es',
  'fr',
  'de',
  'it',
  'pt',
  'nl',
  'pl',
  'sv',
  'ja',
] as const;
export type Locale = (typeof locales)[number];
export const defaultLocale: Locale = 'en';

export const localeNames: Record<Locale, string> = {
  en: 'English',
  es: 'Español',
  fr: 'Français',
  de: 'Deutsch',
  it: 'Italiano',
  pt: 'Português',
  nl: 'Nederlands',
  pl: 'Polski',
  sv: 'Svenska',
  ja: '日本語',
};

export const localeHreflang: Record<Locale, string> = {
  en: 'en',
  es: 'es',
  fr: 'fr',
  de: 'de',
  it: 'it',
  pt: 'pt',
  nl: 'nl',
  pl: 'pl',
  sv: 'sv',
  ja: 'ja',
};
